export const APP_COPY = {
  common: {
    appName: "FinTrack",
    appVersion: "v1.0",
    copyright: "© 2025 FinTrack Systems.",
    currencySymbol: "$",
    syncingWorkspace: "Loading your dashboard...",
    comingSoon: "Coming Soon",
    underConstruction: (tab: string) => `The ${tab} section is currently being built.`,
    backToDashboard: "Back to Dashboard",
    defaultOperator: "User",
  },
  auth: {
    loginTitle: "Welcome Back",
    signUpTitle: "Get Started",
    loginSubtitle: "Log in to manage your finances.",
    signUpSubtitle: "Create an account to start tracking today.",
    emailLabel: "Email Address",
    emailPlaceholder: "hello@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    recoveryMode: "Forgot password?",
    loginButton: "Log In",
    signUpButton: "Create Account",
    noAccess: "Don't have an account? ",
    existingOperator: "Already have an account? ",
    signUpLink: "Sign up",
    loginLink: "Log in",
    brandingText: "Take control of your money and grow your business with ease.",
    verificationSentTitle: "Check your email",
    verificationSentSubtitle: (email: string) => `We've sent a secure login link to ${email}. Click the link to access your account.`,
    proceedToLogin: "Back to Login",
    backToSignUp: "Back to Sign Up",
  },
  onboarding: {
    title: "How will you use FinTrack?",
    subtitle: "Select the options that best describe your needs.",
    personalTitle: "Personal Finance",
    personalDesc: "Track your daily spending and savings",
    businessTitle: "Business Growth",
    businessDesc: "Manage revenue, expenses, and growth plans",
    continueButton: "Go to Dashboard",
    footerNote: "You can update these preferences anytime in settings.",
  },
  sidebar: {
    nav: {
      overview: "Dashboard",
      growth: "Growth Plan",
      analytics: "Analytics",
      milestones: "Goals",
      scan: "Receipts",
      settings: "Settings",
    },
    userFallback: "User",
  },
  dashboard: {
    tabs: {
      overview: "All",
      business: "Business",
      personal: "Personal",
    },
    modals: {
      configTitle: "Plan & Targets",
      configDesc: "Set your revenue goals and pricing tiers.",
      addEntryTitle: "New Transaction",
      editEntryTitle: "Edit Transaction",
      entryDesc: "Record your income and expenses to keep your data up to date.",
      saveStrategy: "Save Settings",
      updateEntry: "Update",
      confirmEntry: "Add Transaction",
    },
    config: {
      coreMrr: "Current Monthly Revenue ($)",
      targetMrr: "Target Monthly Revenue ($)",
      pricingPlans: "Your Pricing Plans",
      addTier: "+ Add Plan",
    },
    forms: {
      expense: "Expense",
      income: "Income",
      description: "Description",
      descriptionPlaceholder: "e.g. Monthly rent or Salary",
      amount: "Amount ($)",
      category: "Category",
      date: "Date",
      account: "Account Type",
      personal: "Personal",
      business: "Business",
    },
    cards: {
      monthlyRevenue: "Total Revenue",
      monthlyBurn: "Total Spending",
      netProfit: "Net Profit",
      mrrLabel: (val: string) => `Base: ${val}`,
      totalOutflow: "Monthly Burn",
      marginLabel: (val: string) => `${val}% Margin`,
    },
    ledger: {
      title: "Recent Transactions",
      status: (count: number) => `${count} transactions tracked.`,
      addIncome: "+ Income",
      addExpense: "+ Spending",
      deleteConfirm: "Remove this transaction?",
      cancel: "Cancel",
      delete: "Delete",
    },
    growth: {
      title: "Growth Insights",
      subtitle: "Revenue Strategy",
      progressLabel: "Progress Toward Goal",
      gapLabel: (val: string) => `${val} left to go`,
      scenariosTitle: "How to reach your goal",
      planLabel: (val: string) => `${val} Plan`,
      tierLabel: "Pricing Tier",
      targetUsers: "Customers Needed",
      updateButton: "Edit Strategy",
    },
    sustainability: {
      title: "Financial Health",
      subtitle: "Monthly Summary",
      dailyBurn: "Spending per day",
      runwaySurplus: "Monthly Profit",
      marginNote: (margin: string) => `Your profit margin is currently ${margin}%.`,
    },
    categories: {
      income: {
        salary: "Salary",
        investment: "Investments",
        general: "Other Income",
      },
      expense: {
        software: "Software & Tools",
        housing: "Rent & Housing",
        food: "Food & Dining",
        transportation: "Travel & Transport",
        utilities: "Bills & Utilities",
        marketing: "Marketing",
        entertainment: "Entertainment",
        business: "Office & Operations",
      }
    }
  }
};
