export const APP_COPY = {
  common: {
    appName: "FinTrack",
    appVersion: "Pro v7.0",
    copyright: "© 2025 FinTrack Pro Systems.",
    currencySymbol: "$",
    syncingWorkspace: "Syncing Workspace...",
    comingSoon: "Coming Soon",
    underConstruction: (tab: string) => `The ${tab} view is currently under construction.`,
    backToDashboard: "Back to Dashboard",
    defaultOperator: "Operator",
  },
  auth: {
    loginTitle: "Terminal Login",
    signUpTitle: "System Access",
    loginSubtitle: "Authenticate to access your dashboard.",
    signUpSubtitle: "Initialize a new financial workspace.",
    emailLabel: "Email Address",
    emailPlaceholder: "operator@fintrack.pro",
    passwordLabel: "Access Password",
    passwordPlaceholder: "••••••••",
    recoveryMode: "Recovery Mode",
    loginButton: "Initiate Session",
    signUpButton: "Create Account",
    noAccess: "No access? ",
    existingOperator: "Existing operator? ",
    signUpLink: "Sign up",
    loginLink: "Log in",
    brandingText: "Master your capital with the industry's most powerful ledger.",
    verificationSentTitle: "Verification Sent",
    verificationSentSubtitle: (email: string) => `We've dispatched a secure access link to ${email}. Please verify your email to initialize your workspace.`,
    proceedToLogin: "Proceed to Login",
    backToSignUp: "Back to Sign Up",
  },
  onboarding: {
    title: "How will you use FinTrack?",
    subtitle: "Select all that apply. This helps us customize your experience.",
    personalTitle: "Personal Finance",
    personalDesc: "Track daily expenses and savings",
    businessTitle: "Business Management",
    businessDesc: "Manage invoices, payroll, and taxes",
    continueButton: "Continue to Dashboard",
    footerNote: "You can always change this later in settings.",
  },
  sidebar: {
    nav: {
      overview: "Overview",
      growth: "Growth Plan",
      analytics: "Analytics",
      milestones: "Milestones",
      scan: "Scan",
      settings: "Settings",
    },
    userFallback: "User",
  },
  dashboard: {
    tabs: {
      overview: "overview",
      business: "business",
      personal: "personal",
    },
    modals: {
      configTitle: "System Configuration",
      configDesc: "Define core financial targets and pricing plans.",
      addEntryTitle: "Add Entry",
      editEntryTitle: "Edit Entry",
      entryDesc: "Maintain your real-time financial ledger.",
      saveStrategy: "Save Strategy",
      updateEntry: "Update Entry",
      confirmEntry: "Confirm Entry",
    },
    config: {
      coreMrr: "Core MRR ($)",
      targetMrr: "Target MRR ($)",
      pricingPlans: "Pricing Plans",
      addTier: "+ Add Tier",
    },
    forms: {
      expense: "Expense",
      income: "Income",
      description: "Description",
      descriptionPlaceholder: "e.g. Server Hosting",
      amount: "Amount ($)",
      category: "Category",
      date: "Date",
      account: "Account",
      personal: "Personal",
      business: "Business",
    },
    cards: {
      monthlyRevenue: "Monthly Revenue",
      monthlyBurn: "Monthly Burn",
      netProfit: "Net Profit",
      mrrLabel: (val: string) => `MRR: ${val}`,
      totalOutflow: "Total Outflow",
      marginLabel: (val: string) => `${val}% Margin`,
    },
    ledger: {
      title: "Financial Ledger",
      status: (count: number) => `Status: ${count} active entries.`,
      addIncome: "+ Income",
      addExpense: "+ Expense",
      deleteConfirm: "Delete entry?",
      cancel: "Cancel",
      delete: "Delete",
    },
    growth: {
      title: "Growth Engine",
      subtitle: "Strategic Analysis",
      progressLabel: "Target MRR Progress",
      gapLabel: (val: string) => `Gap: ${val} Remaining`,
      scenariosTitle: "Scale Scenarios",
      planLabel: (val: string) => `${val} Plan`,
      tierLabel: "Subscription Tier",
      targetUsers: "Target Users",
      updateButton: "Update Strategy",
    },
    sustainability: {
      title: "Sustainability",
      subtitle: "Profit Analysis",
      dailyBurn: "Daily Burn",
      runwaySurplus: "Runway Surplus",
      marginNote: (margin: string) => `Monthly profit surplus is ${margin}% of gross intake.`,
    },
    categories: {
      income: {
        salary: "Salary",
        investment: "Investment",
        general: "General Income",
      },
      expense: {
        software: "Software",
        housing: "Housing",
        food: "Food",
        transportation: "Transportation",
        utilities: "Utilities",
        marketing: "Marketing",
        entertainment: "Entertainment",
        business: "Business Operations",
      }
    }
  }
};
